[project]
name = "AutoBingWallpaper"
version = "1.1.3"
description = "BingWallpaper的轻量实现"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.33.1",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.0",
    "pyinstaller>=6.20.0",
    "ruff>=0.15.12",
    "ty>=0.0.34",
    "typer>=0.25.1",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
